import logging

from outreach_tool import (
    App,
    _digits_only,
    _email_account_from_section,
    _email_account_section,
    _ensure_app_dirs,
    _excel_cell_to_int01,
    _excel_header_norm,
    _helo_domain,
    _imap_append_to_sent,
    _is_email_like,
    _is_phone_like,
    _map_excel_columns,
    _mx_probe_attempt,
    _rcpt_code_verdict,
    _resolve_app_data_dir,
    _sanitize_phone_country_key,
    _score_excel_columns,
    _smtp_handshake_rcpt,
    _verification_log,
    add_lead_to_import,
    cfg,
    check_email_syntax,
    connect_master,
    ensure_contact_replied_columns,
    ensure_contact_sent_column,
    ensure_contact_tracking_columns,
    extract_sender_email,
    get_app_data_dir,
    get_config_file_path,
    get_default_email_account,
    get_email_accounts,
    get_imap,
    get_import_id_for_working_path,
    get_master_db_path,
    get_smtp,
    get_stats_for_import,
    get_unsent,
    get_working_path_for_import,
    import_excel_as_leads,
    import_user_database,
    init_master_schema,
    list_imports,
    list_mx_hosts,
    load_config,
    load_db_contacts,
    lookup_contact_master,
    mark_replied_everywhere,
    mark_sent,
    normalize_email,
    personalize,
    probe_rcpt_on_mx_multiport,
    probe_rcpt_via_configured_smtp,
    register_working_database,
    remove_import,
    resync_import_from_working,
    resolve_phone_location_label,
    run_outreach,
    run_reply_monitor,
    run_warmup,
    save_config,
    save_email_accounts,
    send_discord_alert,
    send_email,
    verify_email,
    write_excel_to_contacts_sqlite,
)

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    app = App()
    app.mainloop()
